# Parameters for path planning
# all units in base units
---
simulation:
 dt: 0.0167 # timestep
platform:
 smoothing:
  ds: 0.005
 profiler:
  v_t: 0.01 # target velocity
  q_lim: [[[-0,1],[-1,1],[-2,2]]] # position, velocity, acceleration joint limits 
 planner:
  platform_to_pose:
   graph:
    goal_dist: 0.025 # maximum distance to goal
    goal_skew: 1 # maximum skew to goal
    directions: [0.02,0.02,0,2.5,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 20000 # max iterations of Astar algorithm
  platform_to_configuration:
   graph:
    goal_dist: 0.025 # maximum distance to goal
    goal_skew: 1 # maximum skew to goal
    directions: [0.02,0.02,0,2.5,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 20000 # max iterations of Astar algorithm
   workspace: # workspace analysis for finding a stable configuration
    padding: [-0.1,-1.0,0,-180,-180,-45] # x, y, z, thetax, thetay, thetaz padding of the analysis space
    scale: [0.1,0.1,0.1,45,45,15] # x, y, z, thetax, thetay, thetaz scale (= resolution) of the analysis space
    mode: "max" # "first", "max"
  patform_align:
    
  platform_to_gripper:
   graph:
    goal_skew: 1 # maximum skew to goal
    directions: [0.01,0.01,0,1,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 20000 # max iterations of Astar algorithm
  platform_to_hold:
   graph:
    goal_skew: 1 # maximum skew to goal
    directions: [0.01,0.01,0,1,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 1000 # max iterations of Astar algorithm 
arm:
 smoothing:
  ds: 0.2 # approximate distance between points on the spline
 profiler:
  v_t: 0.01 # target velocity
  q_lim: [[[-1,1],[-120,120],[-360,360]],
          [[-1,1],[-1,1],[-5,5]],
          [[-1,1],[-1,1],[-5,5]]] # position, velocity, acceleration joint limits
 planner:
  arm_to_pose:
   graph:
    goal_dist: 0.05 # maximum distance to goal
    directions: [0.025,0.025,0.025] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 20000 # max iterations of Astar algorithm
global:
 graph:
  goal_dist: 0.01 # maximum distance to goal
  iter_max: 5000 # max iterations of Astar algorithm 
  workspace: # workspace analysis for finding a stable configuration
   padding: [-0.1,-0.1,0,-180,-180,-45] # x, y, z, thetax, thetay, thetaz padding of the analysis space
   scale: [0.2,0.2,0.1,45,45,45] # x, y, z, thetax, thetay, thetaz scale (= resolution) of the analysis space
   mode: "first" # "first", "max"
 planner:
  fast_platform_to_configuration:
   workspace:
    padding: [-0.1,-1.0,0,-180,-180,-45] # x, y, z, thetax, thetay, thetaz padding of the analysis space
    scale: [0.1,0.1,0.1,45,45,15] # x, y, z, thetax, thetay, thetaz scale (= resolution) of the analysis space
    mode: "first" # "first", "max"
  platform_to_gripper:
   graph:
    goal_skew: 1 # maximum skew to goal
    directions: [0.01,0.01,0,1,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 25 # max iterations of Astar algorithm
  platform_to_hold:
   graph:
    goal_skew: 1 # maximum skew to goal
    directions: [0.01,0.01,0,1,0,0] # x, y, z, thetax, thetay, thetaz search direction and resolution
    iter_max: 25 # max iterations of Astar algorithm
    
   

  

