# Motor parameters
# NOTE: user units: dec degree
# NOTE: ros units: degree
---
can_id: 11 # can node id
factor: 10 # conversion from ros units -> motor controllers' user defined units -> ros units * factor = user units
homing_offset: 0 # Offset (in ros units) of the zero position relative to the position of the reference switch (WARNING: change sign in case of reverse polarity)
homing_method: 35 # Homing method
csp_velocity: 5 # Cyclic synchronous positioning, max velocity (in ros units/s)
csp_acceleration: 5 # Cyclic synchronous positioning, max acceleration (in ros units/s^2)
csp_deceleration: 5 # Cyclic synchronous positioning, max deceleration (in ros units/s^2)
sdos:
 0x2331: # Velocity control parameter set
  0x01: # Proportional gain of speed controller
   value: 2
  0x02: # Integral term of speed controller
   value: 14
   
 0x2332: # Position control parameter set
  0x01: # Proportional gain of position controller
   value: 64
  0x02: # Differential term of position controller
   value: 1
   
 0x2333: # Current control parameter set
  0x01: # Continuous current limit [mA]
   value: 440
  0x02: # Peak current limit [mA]
   value: 1320
  0x03: # Integral term of current controller
   value: 188
   
 0x607E: # Polarity
  0x00: # Bit-coded
   value: [0,0,0,0,0,0,1,1]

 0x607D: # Software position limit
  0x01: # Lower limit of the position range
   value: 1800 # WARNING: change sign in case of reverse polarity
  0x02: # Upper limit of the position range
   value: -1800 # WARNING: change sign in case of reverse polarity 

 0x607F: # Max profile velocity
  0x00: # Maximum permitted speed [min –1 ]
   value: 5530 
   
 0x6085: # Quick stop deceleration
  0x00: # Braking ramp value at Quick stop [1/s 2 ]
   value: 30000 
   
 0x6091: # Gear ratio
  0x01: # Number of motor revolutions 
   value: 66  
  0x02: # Number of revolutions of the output shaft
   value: 10 
   
 0x6092: # Feed constant
  0x01: # Feed in user units
   value: 3600 # 3600 cdeg 
  0x02: # Number of revolutions of the outputshaft
   value: 60 # worm gear ratio

